function(chess_enable_profiling target)
    if(NOT CHESS_ENABLE_PROFILING)
        return()
    endif()
    if(MSVC)
        message(STATUS "The gprof profile preset is unavailable with MSVC")
        return()
    endif()
    target_compile_options(${target} PRIVATE -pg -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -pg)
endfunction()
